feat(preview): Vuetify 3 + Vite preset
vuetifyjs/vue-cli-plugins pull request #248
Opened 2021-03-05 07:56 UTC by ElijahKotyluk

### To test
```bash
vue create my-app
```

#### Vue prompt
```bash
? Please pick a preset: (Use arrow keys)
    Default ([Vue 2] babel, eslint) 
  ❯ Default (Vue 3 Preview) ([Vue 3] babel, eslint) 
    Manually select features 
```

#### cd into app dir
```bash
cd my-app
```

#### Install vuetify/vue-cli-plugins
```bash
yarn add -D '../local/path/to/vue-cli-plugins-vuetify'
```

#### Invoke vuetify
```bash
vue invoke vuetify
```

#### Vuetify prompt
```bash
? Choose a preset: (Use arrow keys)
  Default (recommended) 
❯ Preview (v3 + vite)
  Prototype (rapid development) 
  V3 (alpha) 
  Configure (advanced) 
```

#### Run app
```bash
yarn dev
```

2021-03-05 14:55 UTC, johnleider requested changes

2021-03-05 14:55 UTC, johnleider commented on packages/vue-cli-plugin-vuetify/generator/index.js
> +      'dev': 'vite',
```suggestion
        'serve': 'vite preview',
        'build': 'vite build',
        'dev': 'vite',
```

2021-03-05 14:55 UTC, johnleider commented on packages/vue-cli-plugin-vuetify/generator/templates/v3/src/components/HelloWorld.js.vue
> +          <%_ } _%>
```suggestion
          <div>Welcome to the Vuetify 3 Alpha</div>
```

2021-03-05 14:55 UTC, johnleider commented on packages/vue-cli-plugin-vuetify/generator/templates/v3/src/components/HelloWorld.js.vue
```suggestion

<%_ if (useVite) { _%>
          <small>Vite Preview</small>
<%_ } _%>

```

2021-03-05 14:55 UTC, johnleider commented on packages/vue-cli-plugin-vuetify/generator/templates/v3/src/vite.config.js
> +  },
```suggestion
  define: { 'process.env': {} },
```

2021-03-06 22:17 UTC, Djaler commented
How ironically, isn't it? Using old tooling to install the new one

2021-03-07 05:25 UTC, johnleider requested changes
Looking really good 😀

2021-03-07 05:25 UTC, johnleider commented on packages/vue-cli-plugin-vuetify/generator/templates/v3/src/index.vite.html
> +    <title>Vite App</title>
```suggestion
    <title>Vuetify 3 Vite Preview</title>
```

2021-03-07 05:25 UTC, johnleider commented on packages/vue-cli-plugin-vuetify/generator/templates/v3/src/components/HelloWorld.js.vue
> +        href: 'https://vuetifyjs.com/en/introduction/roadmap/',
```suggestion
        href: 'https://vuetifyjs.com/introduction/roadmap/',
```

2021-03-07 05:25 UTC, johnleider commented on packages/vue-cli-plugin-vuetify/util/presets.js
> +  preview: 'Preview (vuetify 3 + vite)',
```suggestion
  preview: 'Preview (Vuetify 3 + Vite)',
```

2021-03-07 05:26 UTC, ElijahKotyluk commented on packages/vue-cli-plugin-vuetify/generator/templates/v3/src/components/HelloWorld.js.vue
> +        href: 'https://vuetifyjs.com/en/introduction/roadmap/',
Ah, good catch!

2021-03-08 19:35 UTC, johnleider approved these changes

2021-03-17 18:24 UTC, merged

2021-03-18 15:16 UTC, vallemar commented
Hi @johnleider,

When is this functionality expected to be available?

Thanks!

2021-03-18 16:13 UTC, johnleider commented
As soon as it's released.